feat(share): #MC-26 add back security to don't share default calendar
OPEN-ENT-NG/calendar pull request #100
Opened 2022-07-25 08:46 UTC by adrienFro

## Describe your changes
add in back a security to can't share default calendar
## Checklist tests
Test if the flow is the same than before
## Issue ticket number and link
https://entsupport.gdapublic.fr/browse/MC-26
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-07-25 09:01 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                                if (Boolean.TRUE.equals(res)){
donc si c'est false OU null on fait le reste ?

2022-07-25 09:28 UTC, adrienFro commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                    request.pause();
This line is used to pause the request to avoid an already read exception.

2022-07-25 09:31 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                                    shareResource(request, "calendar.share", false, params, "title");
magic string

2022-07-25 09:32 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/core/constants/Field.java
> +
Est ce utile ?

2022-07-25 09:34 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                    request.pause();
il y a pas besoin de la resume ? @JinDouang

2022-07-25 12:37 UTC, JinDouang requested changes

2022-07-25 12:37 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                    request.pause();
Effectivement j'ai du mal à voir l'utilité..

2022-07-25 12:37 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                            .onFailure(err -> renderError(request));
Il va falloir dire ce qu'on fait si jamais user est bien différent à null 🤔

2022-07-25 12:37 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                            )
indentation parenthese avec la bracket

2022-07-25 12:37 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
>                          badRequest(request, "invalid.id");
A mon avis au dessus tu peux la rendre en mode lambda

2022-07-25 15:21 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                        )
})

2022-07-25 15:34 UTC, alicedraillard approved these changes

2022-07-26 08:26 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                request.pause();
Le choix de pauser la requête est parce que derrière il y a une méthode de type future dans laquelle on la sollicite dans son callback pour faire les interactions et à ce moment là la requête aurait déjà été "résolu".
On pause et résume à la fin de la future pour continuer les intéractions

2022-07-26 08:26 UTC, JinDouang approved these changes

2022-07-26 08:28 UTC, merged