"feat(api): #MC-161 add trace api
OPEN-ENT-NG/calendar pull request #101
Opened 2022-07-25 10:12 UTC by AyaNADINI

## Describe your changes
Providing a way to determine what exactly is happening with HTTP request, to diagnose unexpected or undesirable behavior.
To deal with this, we add API trace to trace HTTP request on specific routes.

## Checklist tests
Request tested using Postman
Traces table are filled in mongodb

## Issue ticket number and link
MC-161 : https://entsupport.gdapublic.fr/browse/MC-161

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ]  I have performed a self-review of my code

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-07-25 12:45 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="SHARE CALENDAR_SUBMIT")
utilise toujours un _, pas d'espace ==> SHARE_CALENDAR_SUBMIT

2022-07-25 12:45 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="SHARE CALENDAR_REMOVE")
utilise toujours un _ (pas d'espace) ==> SHARE_CALENDAR_REMOVE

2022-07-25 12:46 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +
pourquoi supprimer le list ?

2022-07-25 12:46 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="SHARE_RESOURCE")
SHARE_CALENDAR

2022-07-25 12:46 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +    @Trace(value="SHARE_RESOURCE")
SHARE_EVENT

2022-07-26 15:46 UTC, alicedraillard approved these changes

2022-07-26 15:48 UTC, vava56754 approved these changes

2022-07-26 16:01 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="CREATE_CALENDAR")
Est-ce que ce ne serait pas mieux de faire une liste regroupant tous les traces dans un fichier appart. En peu comme Field.java

2022-07-27 07:30 UTC, JinDouang requested changes

2022-07-27 07:30 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="CREATE_CALENDAR")
Je suis d'accord, une constant "Actions" pour qu'il soit spécifique aux traces

2022-07-27 07:30 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Trace(value="CREATE_CALENDAR")
`@Trace(Actions.CREATE_CALENDAR` pas besoin de rajouter "value"

2022-07-27 08:10 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/core/constants/Actions.java
> +    public static final String IMPORT_ICL = "ImportIcal";
IMPORT_ICAL

2022-07-27 08:58 UTC, alicedraillard approved these changes

2022-07-27 09:22 UTC, JinDouang commented
@alicedraillard Pour les traces on ne souhaite pas stocker le payload également ?

2022-07-27 10:47 UTC, BastienBenard approved these changes

2022-07-27 13:00 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/core/constants/Actions.java
> +    public static final String CREATE_CALENDAR = "createCalendar";
pourquoi pas en SNAKE_CASE ?

2022-07-27 13:05 UTC, adrienFro approved these changes

2022-07-27 13:34 UTC, JinDouang approved these changes

2022-07-27 13:37 UTC, merged