fix(rbs): #MC-164 secure rbs calls
OPEN-ENT-NG/calendar pull request #102
Opened 2022-07-26 13:53 UTC by alicedraillard

## Describe your changes
Module works when no conf is added

## Checklist tests
choose platform without enableRbs = true config, try to create event

## Issue ticket number and link
#MC-164 https://entsupport.gdapublic.fr/browse/MC-164

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-07-26 14:45 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +            if ($scope.ENABLE_RBS) $scope.rbsEmitter.emitBookingInfo(Behaviours.applicationsBehaviours.rbs.eventerRbs.INIT_BOOKING_INFOS, $scope.calendarEvent);
secure behaviours calls

2022-07-26 14:45 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +                if ($scope.ENABLE_RBS) $scope.rbsEmitter.emitBookingInfo(Behaviours.applicationsBehaviours.rbs.eventerRbs.CAN_EDIT_EVENT, true);
secure behaviours calls

2022-07-26 14:45 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +            if ($scope.ENABLE_RBS) $scope.rbsEmitter.emitBookingInfo(Behaviours.applicationsBehaviours.rbs.eventerRbs.CLOSE_BOOKING_INFOS);
secure behaviours calls

2022-07-27 07:32 UTC, JinDouang requested changes

2022-07-27 07:32 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +            $scope.rbsEmitter = new RbsEmitter($scope, !!ENABLE_RBS);
pourquoi ne pas utiliser $scope.ENABLE_RBS plutôt ?

2022-07-27 07:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +            $scope.rbsEmitter = new RbsEmitter($scope, !!ENABLE_RBS);
https://github.com/OPEN-ENT-NG/calendar/blob/51dee1109f993941da84db457e97295169141e2f/src/main/resources/public/ts/controllers/controller.ts#L1420

2022-07-27 07:36 UTC, BastienBenard commented on src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
> +                    break;
Si tu a plusieurs cas qui font la meme chose tu peux faire:
```
                case Behaviours.applicationsBehaviours.rbs.eventerRbs.INIT_BOOKING_INFOS:
                case Behaviours.applicationsBehaviours.rbs.eventerRbs.CAN_EDIT_EVENT:
                case Behaviours.applicationsBehaviours.rbs.eventerRbs.UPDATE_BOOKING_INFOS:
                    this.scope.$broadcast(event, data);
                    break;
                case Behaviours.applicationsBehaviours.rbs.eventerRbs.CLOSE_BOOKING_INFOS:
                    this.scope.$broadcast(event);
                    break;
```

2022-07-27 07:39 UTC, BastienBenard commented on src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
>          }
il faut returner quelque chose si l'on ne passe pas dans le if

2022-07-27 09:40 UTC, JinDouang approved these changes

2022-07-27 13:34 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +                    return (bookingDeletionInfo && bookingDeletionInfo['vm'] && bookingDeletionInfo['vm'].canDeleteBooking()
eliminate undefined warning

2022-07-27 13:39 UTC, BastienBenard approved these changes

2022-07-27 13:50 UTC, JinDouang approved these changes

2022-07-27 14:05 UTC, merged