feat(calendar): #MC-178 add new display Date
OPEN-ENT-NG/calendar pull request #107
Opened 2022-08-11 14:51 UTC by adrienFro

## Describe your changes
add new display Date
## Checklist tests
- check if the change of display is right 
## Issue ticket number and link
https://jira.support-ent.fr/browse/MC-178
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-11 15:01 UTC, qperie approved these changes

2022-08-11 15:02 UTC, alicedraillard requested changes

2022-08-11 15:02 UTC, alicedraillard commented on src/main/resources/public/ts/model/CalendarEvent.ts
> +            notifStartMoment: this.notifStartMoment.format("DD/MM/YYYY : HH:mm"),
impacte l'objet enregistré, modification à faire ailleurs dans le code

2022-08-11 17:03 UTC, JinDouang commented
Il faudrait un screenshot pour voir

2022-08-11 17:03 UTC, JinDouang commented on src/main/resources/public/ts/model/CalendarEvent.ts
> +            notifStartMoment: this.notifStartMoment.format("DD/MM/YYYY : HH:mm"),
Il faudrait une nouvelle méthode si c'est juste l'affichage

2022-08-11 17:04 UTC, JinDouang requested changes

2022-08-11 17:04 UTC, JinDouang commented on src/main/resources/public/ts/model/CalendarEvent.ts
> +            notifEndMoment: this.notifEndMoment.format("DD/MM/YYYY : HH:mm"),
idem que le commentaire d'alice

2022-08-12 08:50 UTC, alicedraillard requested changes

2022-08-12 08:50 UTC, alicedraillard commented on src/main/resources/public/template/tooltip-template.html
> +            [[changeDateMultipleDays(item.notifStartMoment)]] - [[changeDateMultipleDays(item.notifEndMoment)]]
change le nom pour que la fonction puisse être + générale

2022-08-12 08:50 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +import format = require("core-js/fn/date/format");
pourquoi cet import ?

2022-08-12 08:50 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +
rajouter
$scope.function1= (date: Date) => {
            return DateUtils.getSimpleDateAndTimeFormat(date, FORMAT.displayFRDate);
 }

$scope.function2 = (date: Date) => {
            return DateUtils.getSimpleDateAndTimeFormat(date, FORMAT.displayTime);
 }
et dans le HTML tu mets [[function1(item.notifStartMoment)]] : [[function2(item.notifStartMoment)]]  ... etc

2022-08-12 08:50 UTC, alicedraillard commented on src/main/resources/public/template/tooltip-template.html
> +            [[changeDateMultipleDays(item.notifStartMoment)]] - [[changeDateMultipleDays(item.notifEndMoment)]]
Utilise le html entity pour - et :

2022-08-12 09:45 UTC, JinDouang requested changes

2022-08-12 09:45 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatFRDate = (date: Date) => {
Typage

2022-08-12 09:45 UTC, JinDouang commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatTime = (date: Date) => {
Typage

2022-08-12 09:45 UTC, JinDouang commented on src/main/resources/public/ts/utils/date.utils.ts
> +    static getSimpleTimeFormat = (date: Date, parsingFormat?: string): string => {
Fais des TUs de date sur tes 2 methodes
On aimerait savoir en detail ce que ca vaut

2022-08-12 09:48 UTC, alicedraillard commented on src/main/resources/public/ts/utils/date.utils.ts
> +    static getFRDateFormat = (date: Date, parsingFormat?: string): string => {
le bus c'est d'avoir 2 méthodes dans le controller.ts mais une seule dans le date.utils.ts (si tu regardes tu peux voir que le contenu de tes méthodes est quasi pareil)

2022-08-23 10:25 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatFRDate = (date: Date) => {
Il manque le typage de retour

2022-08-23 10:25 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatTime = (date: Date) => {
Il manque le typage de retour

2022-08-23 10:29 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatFRDate = (date: Date) => {
Il manque le typage de retour

2022-08-23 10:29 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/controller.ts
> +        $scope.formatTime = (date: Date) => {
Il manque le typage de retour

2022-08-23 12:08 UTC, flmartineau approved these changes

2022-08-23 12:29 UTC, alicedraillard approved these changes

2022-08-23 13:01 UTC, BastienBenard approved these changes

2022-08-23 13:06 UTC, merged