feat(view): #MC-167 add external calendar form
OPEN-ENT-NG/calendar pull request #123
Opened 2022-09-15 13:24 UTC by alicedraillard

## Describe your changes
- create calendar import popup with its form rules
- create front-end endpoints for later use

## Checklist tests
try to open, fill and close the form

## Issue ticket number and link
#MC-167 https://jira.support-ent.fr/browse/MC-167

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-15 13:35 UTC, alicedraillard commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +        this.$scope.$parent.$eval(this.$scope.vm.onInitNewCalendar)(calendar);
sert à faire remonter l'info au controller

2022-09-15 13:35 UTC, alicedraillard commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +        this.$scope.vm.calendarPlatforms = Object.keys(CALENDAR_PLATFORMS).filter(key => !isNaN(Number(CALENDAR_PLATFORMS[key])));
transforme l'enum en Array<string>

2022-09-15 13:50 UTC, BastienBenard commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +        let extCalendarForm = angular.element(document.getElementById("external-calendar-form")).scope();
typage

2022-09-15 13:54 UTC, BastienBenard approved these changes

2022-09-15 14:09 UTC, qpic-cgi requested changes

2022-09-15 14:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +        this.$scope.$parent.$eval(this.$scope.vm.onInitNewCalendar)(calendar);
Utilise le link comme dans l'exemple ci-dessous:
https://github.com/CGI-OPEN-ENT-NG/minibadge/blob/MBA-2/src/main/resources/public/ts/directives/infinite-scroll/infinite-scroll.directive.ts#L29
Prend l'exemple de la fonction scrolled, qui est une propriété de la directive.
Si tu as des doutes, tu peux voir avec Bastien

2022-09-15 14:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +        this.$scope.$parent.$eval(this.$scope.vm.onCreateExternalCalendar)(this.$scope.vm.calendar);
cf src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts

2022-09-15 14:53 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/controller.ts
> +            // }
utile ce com ?

2022-09-16 10:02 UTC, JinDouang requested changes

2022-09-16 10:02 UTC, JinDouang commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +        this.onCreateExternalCalendar()(this.$scope.vm.calendar);
```suggestion
               this.$scope.vm.createExternalCalendar()(this.$scope.vm.calendar);

```
plutôt ?

Si ça marche pas, tu pourrais l'appeler dans ton link

2022-09-16 10:02 UTC, JinDouang commented on src/main/resources/public/ts/services/calendar.service.ts
> +    updateExternalCalendar(calendar: Calendar): Promise<AxiosResponse> {
C'est nécessaire `Calendar ` parce que tu auras à l'avenir besoin d'autre choses qu'icsLink ?
Sinon tu pourrais passer un string directement

2022-09-19 15:16 UTC, qpic-cgi commented on src/main/resources/public/ts/app.ts
> +ng.directives.push(externalCalendarAddition);
pourquoi ne pas faire avec tes directives ce que tu fais au dessus avec tes controllers et tes services ?

2022-09-19 15:16 UTC, qpic-cgi commented on src/main/resources/public/ts/app.ts
> +ng.directives.push(externalCalendarAddition);
pourquoi ne pas faire avec tes directives ce que tu fais au dessus avec tes controllers et tes services ?

2022-09-19 15:29 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +    vm: ICalendarItemProps;
verdict ?  malgré le binding intelligent on force le typage ?

2022-09-19 15:35 UTC, alicedraillard commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +    onCreateExternalCalendar?(): (calendar: Calendar) => void;
parce qu'on le récupère en props

2022-09-20 07:49 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +    onCreateExternalCalendar?(): (calendar: Calendar) => void;
ça implique de faire: onCreateExternalCalendar?() ?

2022-09-20 07:51 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
> +    vm: ICalendarItemProps;
je n'ai pas compris :S

2022-09-20 08:23 UTC, JinDouang commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +    onCreateExternalCalendar?(): (calendar: Calendar) => void;
C'est un peu trop tricky pour l'usage d'angularjs pour link

Le truc c'est que son IViewModel extends aussi les props mais on ne veut pas nécessairement les utiliser dans la class Controller si c'est que des usages pour déclencher un callback 

On a trouvé https://docs.angularjs.org/api/ng/service/$parse qui permet de déclencher des expressions avec des params + facilement mais il faut le faire dans link (jouable dans le controller mais c'est pas très directive angularjs 

https://docs.angularjs.org/guide/directive ("_Directives that want to modify the DOM typically use the link option..._")

Dans un premier on part sur ça

2022-09-20 08:23 UTC, JinDouang approved these changes

2022-09-20 08:35 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
> +    onCreateExternalCalendar?(): (calendar: Calendar) => void;
Okey je vois, c'est un parti prix, je comprend

2022-09-20 08:38 UTC, qpic-cgi approved these changes

2022-09-20 13:56 UTC, qpic-cgi requested changes

2022-09-20 13:56 UTC, qpic-cgi commented on src/main/resources/public/ts/model/Calendar.ts
> +        let calendarJson: any = {
any ?

2022-09-20 15:05 UTC, qpic-cgi approved these changes

2022-09-20 15:11 UTC, merged