feat(tooltip): #MC-206 add last update in external calendar tooltip
OPEN-ENT-NG/calendar pull request #135
Opened 2022-09-27 14:48 UTC by alicedraillard

## Describe your changes
add tooltip that displays external calendar's last update

## Checklist tests
place mouse over external calendar in sidebar and check tooltip

## Issue ticket number and link
#MC-206 https://jira.support-ent.fr/browse/MC-206

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-28 08:01 UTC, sjollois approved these changes

2022-09-28 08:08 UTC, JinDouang requested changes

2022-09-28 08:08 UTC, JinDouang commented on src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
> +import {idiom as lang} from "entcore/types/src/ts/idiom";
Tu n'as pas l'air de l'utiliser

2022-09-28 08:08 UTC, JinDouang commented on src/main/resources/public/ts/model/Calendar.ts
> +    updated: object;
d'où viennent ces fields que tu as rajouté ? "created", "modified" et "updated"

2022-09-28 08:08 UTC, JinDouang commented on src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
> +        return moment(this.$scope.vm.calendar.updated['$date']).format(format);
d'où vient ce scope "updated" au niveau du controller ?

2022-09-28 09:29 UTC, alicedraillard commented on src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
> +        return moment(this.$scope.vm.calendar.updated['$date']).format(format);
c'est un nouveau champ qui sera conservé en bdd (comme modified et created qui existent actuellement)

2022-09-28 12:57 UTC, JinDouang requested changes

2022-09-28 12:57 UTC, JinDouang commented on src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
> +        return moment(this.$scope.vm.calendar.updated['$date']).format(format);
vu avec @alicedraillard pour adapter le model Calendar

2022-09-28 12:57 UTC, JinDouang commented on src/main/resources/public/ts/model/Calendar.ts
> +    updated: object;
vu avec @alicedraillard pour adapter le model Calendar

2022-09-29 08:45 UTC, JinDouang requested changes

2022-09-29 08:45 UTC, JinDouang commented on src/main/resources/public/ts/model/Calendar.ts
> +                console.log(FORMAT.formattedISODate);
console.log

2022-09-29 09:40 UTC, JinDouang approved these changes

2022-09-29 09:41 UTC, merged