feat(api): #MC-204 secure API endpoints
OPEN-ENT-NG/calendar pull request #142
Opened 2022-10-04 14:25 UTC by alicedraillard

## Describe your changes
the following actions cannot be applied to external calendars/events of external calendars

## Checklist tests
try to call apis with postman

## Issue ticket number and link
[MC-204](https://jira.support-ent.fr/browse/MC-204)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-04 14:26 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Put("/:id/url")
change route because it was the same as the ical import (will be fixed in later tickets)

2022-10-04 14:35 UTC, qpic-cgi commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +                                        params.put("profilUri", "/userbook/annuaire#" + user.getUserId() + "#" + user.getType());
Field constants ici

2022-10-04 14:35 UTC, qpic-cgi commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                                        message.put("id", calendarId);
Field constant ici

2022-10-04 14:36 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                            if(Boolean.FALSE.equals(isExternal)) {
indentation

2022-10-04 14:37 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                                                shareResource(request, "calendar.share", false, params, Field.TITLE);
fin indentation

2022-10-04 14:37 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +                                    if(Boolean.FALSE.equals(isExternal)) {
indentation

2022-10-04 14:37 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +                                        eventHelper.addEventToUsersCalendar(id, body, user, host, lang);
fin indentation

2022-10-04 14:37 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                        if (isEventValid(object, request)) {
indentation

2022-10-04 14:37 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                        }
fin indentation

2022-10-04 14:38 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                            crudService.update(eventId, object, user, new Handler<Either<String, JsonObject>>() {
indentation

2022-10-04 14:38 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                            });
fin indentation

2022-10-04 14:38 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                        if(Boolean.FALSE.equals(isExternal)) {
indentation

2022-10-04 14:38 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                    .onFailure(err -> renderError(request));
fin indentation

2022-10-04 14:39 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                eventService.getIcal(calendarId, user, new Handler<Message<JsonObject>>() {
indentation

2022-10-04 14:39 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                });
fin indentation

2022-10-04 14:39 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                    if(Boolean.FALSE.equals(isExternal)) {
indentation

2022-10-04 14:40 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                        eventService.importIcal(calendarId, icsContent, user, requestInfo, defaultResponseHandler(request));
fin indentation

2022-10-04 14:41 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +                                        params.put("profilUri", "/userbook/annuaire#" + user.getUserId() + "#" + user.getType());
indentation

2022-10-04 14:41 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                                                        message.put("id", calendarId);
indentation

2022-10-05 08:46 UTC, JinDouang requested changes

2022-10-05 08:46 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
>      @SecuredAction("calendar.create")
Je ne l'avais peut-être pas relevé (je sais pas si tu as crée cet endpoint) mais sache que niveau droit, tu auras 2 fois "calendar.create" qui auront ta méthode synxExternalCalendar et createCalendar (https://github.com/OPEN-ENT-NG/calendar/blob/eeaf349bdba221f0016a47c0f07c24c022fcb3b4/src/main/java/net/atos/entng/calendar/controllers/CalendarController.java#L111)

"calendar.create" qui te sera affiché 2 fois dans ta console admin pour attribuer les droits
Ils auront pas les mêmes type de data comme c'est 2 méthodes différentes mais voilà..à part pour trouver un nommage ou faire une classe de sécurité si tu veux que ça prenne le même droit

2022-10-05 08:46 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +        QueryBuilder query = QueryBuilder.start("_id").is(calendarEventId);
magic string

2022-10-05 08:46 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +        mongo.findOne(CALENDAR_EVENT_COLLECTION, MongoQueryBuilder.build(query), validResultHandler(result -> {
Cette méthode qui te fait un findOne, on peut pas l'externaliser pour le rendre globale ?

Elle peut être intéressante de le mettre dans une méthode car il te permet de récupérer un calendarEvent par son id (ou autre critère qui fait que tu aurais que un seul unique résultat ?)

Edit: finalement après quelque recherche, tu as déjà une méthode qui te permet de faire la même chose : 
https://github.com/OPEN-ENT-NG/calendar/blob/eeaf349bdba221f0016a47c0f07c24c022fcb3b4/src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java#L382

Tu peux la polymorpher pour qu'elle soit une Future 

```
@Override
    public Future<JsonObject> getCalendarEventById(String eventId) {
        Promise<JsonObject> promise = Promise.promise();
        getCalendarEventById(eventId, event -> {
            if (event.isLeft()) {
                // gestion log etc
                promise.fail(event.left().getValue());
            } else {
                promise.complete(event.right().getValue());
            }
        });
        return promise.future();
    }
```

2022-10-05 08:46 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +        return this.calendarService.arrayContainsExternalCalendarId(calendarEvent.getJsonArray(Field.CALENDAR).getList());
Pourquoi ne pas appeler ton service directement ?
Tu pourrais faire ton calendarEvent.getJsonArray directement depuis ton result.right().getValue() (méthode `isEventFromExternalCalendar`)

2022-10-05 08:46 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +        mongo.find(this.collection, query, validResultsHandler(result -> {
Il n'y aurait pas une possibilité de faire évoluer ta méthode list avec tes critères ?

Ca t'éviterai de faire une requête à chaque usage pour ta logique métier

2022-10-06 13:46 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @SecuredAction("calendar.sync")
Le calendar.sync ca pourrait valloir le coup de mettre ca dans un fichier constants (Rights comme dans Présences)

2022-10-06 13:56 UTC, JinDouang requested changes

2022-10-06 13:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
> +                // gestion log etc
commentaire ?

2022-10-06 13:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +        this.arrayContainsExternalCalendarId(Collections.singletonList(calendarId))
Vu avec alice pour voir si au final isExternalCalendar est utile

2022-10-07 10:25 UTC, JinDouang approved these changes

2022-10-07 11:35 UTC, JinDouang approved these changes

2022-10-07 13:26 UTC, merged