feat(sync): #MC-184 get and save calendar + events from url
OPEN-ENT-NG/calendar pull request #146
Opened 2022-10-17 16:11 UTC by alicedraillard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-17 16:16 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> -            String url = request.params().get(Field.URL);
a new endpoint has been created instead of reusing this one

2022-10-17 16:21 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    @Get("/:id/url")
To be used by front-end to check if the calendar is still updating

2022-10-18 11:51 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> -            String url = request.params().get(Field.URL);
external calendar creation (1st import) now has its own API)

2022-10-18 12:00 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +    private final net.atos.entng.calendar.helpers.CalendarHelper calendarHelper;
Utilise un import

2022-10-18 14:37 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                String errMessage = String.format("[Calendar@%s::externalCalendarFirstSync]:  " +
[Calendar@%s::getAndSaveExternalCalendarEvents]

2022-10-18 14:38 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                    JsonObject calendar = calendarList.getJsonObject(0).put(Field.ISUPDATING, true);
Fais une vérif sur calendarList, si jamais il est vide.

2022-10-18 14:41 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/security/ShareEventConf.java
> +import fr.wseduc.mongodb.MongoUpdateBuilder;
Tu te sers de ces imports ?

2022-10-18 14:43 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +                    Boolean fieldValue = result.getJsonObject(0).getBoolean(field, null);
verif si result est null

2022-10-18 14:44 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +                    log.error("[Calendar@CalendarService::hasExternalCalendarId]: an error has occurred while checking external calendars: ",
[Calendar@CalendarService::checkBooleanField]

2022-10-18 14:44 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +                log.error("[Calendar@CalendarService::update]: an error has occurred while updating calendar: ",
Mauvais log

2022-10-18 14:47 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
> +            mongo.save(collection, body, validActionResultHandler(handler));
` mongo.save(collection !== null) : collection : this.collection , body, validActionResultHandler(handler));`

2022-10-18 14:51 UTC, qperie approved these changes

2022-10-18 14:51 UTC, qperie commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +            promise.complete(result.right().getValue());
A mettre dans un else ou alors return dans le if en cas de result.isLeft() au dessus ?

2022-10-18 14:51 UTC, qperie commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +            promise.complete();
A mettre dans un else ou alors return dans le if en cas de result.isLeft() au dessus ?

2022-10-18 15:01 UTC, aymericdevriesere commented on src/main/java/net/atos/entng/calendar/Calendar.java
> +        ServiceFactory serviceFactory = new ServiceFactory(vertx, Neo4j.getInstance(), Sql.getInstance(), MongoDb.getInstance(), initWebclient());
Le webclient aurait pu être déclaré direct dans le service factory non ?

2022-10-18 15:05 UTC, aymericdevriesere commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                    String message = String.format("[Calendar@%s::updateCalendar]:  an error has occurred while " +
pourquoi le fait que le cal soit externe n'est spécifié que dans l'erreur et pas dans le nom de la fonction

2022-10-18 15:07 UTC, aymericdevriesere commented on src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
> +            switch (action) {
pas de default case

2022-10-18 15:08 UTC, aymericdevriesere commented on src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
> +                                String errMessage = String.format("[Calendar@%s::importIcal] An error has occured" +
Mauvais nommage dans l'erreur

2022-10-18 15:20 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/Calendar.java
> +        ServiceFactory serviceFactory = new ServiceFactory(vertx, Neo4j.getInstance(), Sql.getInstance(), MongoDb.getInstance(), initWebclient());
De cette maniere on peut ne pas avoir les mm options pour Calendar et ExternalCalendarImport qui est porté par un worker

2022-10-19 08:54 UTC, JinDouang requested changes

2022-10-19 08:54 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
> +        try {
Tu n'as pas besoin de try catch (commentaire en dessous), si ?

2022-10-19 10:02 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +                        promise.fail(message);
je complete la promise si j'arrive à récupérer le fieldValue (qui est un booléen), sinon je fail (sur cette ligne c'est parce que l'objet que je récupère est null)

2022-10-19 12:57 UTC, JinDouang requested changes

2022-10-19 12:57 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
> +                        promise.fail(message);
Oui mais ton fieldValue peut également être null non ? Comme tu le définis par défaut…
Sachant que c'est un Boolean que tu renvoies au final

`result.getJsonObject(0).getBoolean(field, null);` peut également te renvoyer null

si tu es dans ton else à tout moment tu pourrais compléter avec null (mais aujourd'hui tu le fail comme si c'était une exception)

2022-10-19 13:01 UTC, flmartineau approved these changes

2022-10-19 15:02 UTC, aymericdevriesere approved these changes

2022-10-19 16:08 UTC, BastienBenard approved these changes

2022-10-19 16:57 UTC, JinDouang requested changes

2022-10-19 16:57 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
> +import java.net.MalformedURLException;
Import non utilisé

2022-10-19 16:57 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
> +import net.fortuna.ical4j.util.Strings;
Non utilisé

2022-10-19 16:57 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +                    Renders.badRequest(request);
Ca serait plus un renderError puisque tu vas tomber dans une exception (ton onFailure)
```suggestion
                   Renders.renderError(request);
```

2022-10-19 16:57 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
> +import fr.wseduc.webutils.Either;
Non utilisé

2022-10-20 07:37 UTC, merged