fix(search-engine): #MC-264 allow research in Calendar
OPEN-ENT-NG/calendar pull request #182
Opened 2022-11-23 13:50 UTC by alicedraillard

## Describe your changes
- Match field change from verison 0.7.0 : field "calendar" in an event is no longer a String but an array
- Changes in i18n

## Checklist tests
try to research an event, you should get the info concerning it

## Issue ticket number and link
[MC-264](https://jira.support-ent.fr/browse/MC-264)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-23 14:01 UTC, sjollois requested changes

2022-11-23 14:01 UTC, sjollois commented on src/main/java/net/atos/entng/calendar/event/CalendarSearchingEvents.java
> +				final String idCalendar = j.getJsonArray("calendar", new JsonArray()).getString(0);
verif par rapport au size du JsonArray de "calendar" pour ne pas avoir d'exception

2022-11-23 14:06 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/event/CalendarSearchingEvents.java
> +				final String idCalendar = j.getJsonArray("calendar", new JsonArray()).getString(0);
MagicString

2022-11-23 14:07 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/event/CalendarSearchingEvents.java
>  						j.getString("location", ""), j.getString("startMoment"), j.getString("endMoment")));
Magic String

2022-11-23 14:07 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/event/CalendarSearchingEvents.java
> +			descriptionRes = i18n.translate("calendar.search.description.min", "default-domain", locale, title, sDateRes,
"default-domain" MagicString

2022-11-23 14:09 UTC, BastienBenard reviewed
Est ce que tu peux faire un test sur la fonction formatSearchResult ?

2022-11-24 08:39 UTC, aymericdevriesere approved these changes

2022-11-24 14:45 UTC, sjollois approved these changes

2022-11-25 15:03 UTC, BastienBenard approved these changes

2022-11-25 15:03 UTC, BastienBenard commented on src/test/java/net/atos/entng/calendar/event/CalendarSearchingEventsTest.java
> +//        }).when(i18n).translate(Mockito.anyString(), Mockito.anyString(), Mockito.anyString());
c'est utile ?

2022-11-25 15:03 UTC, BastienBenard commented on src/test/java/net/atos/entng/calendar/event/CalendarSearchingEventsTest.java
> +//"modified":{"$date":1669039699414}}]
c'est utile ?

2022-11-25 15:26 UTC, merged