feat(zimbra) : #MC-260 check if external calendar has platform
OPEN-ENT-NG/calendar pull request #194
Opened 2022-12-29 16:50 UTC by alicedraillard

## Describe your changes
Platform and url are checked before creating external calendar

## Checklist tests
call api with object :
{
    "title" : "Test",
    "color" : "grey",
    "isExternal" : true,
    "platform" : "Zimbra"
}

## Issue ticket number and link
[MC-260](https://jira.support-ent.fr/browse/MC-260)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-12-30 09:28 UTC, Sofianebernoussi approved these changes

2023-01-03 08:57 UTC, JinDouang requested changes

2023-01-03 08:57 UTC, JinDouang commented on deployment/calendar/conf.json.template
> +        "enable-zimbra": ${enableZimbra}
A mettre dans la conf.j2 également

2023-01-03 09:07 UTC, JinDouang approved these changes

2023-01-03 09:10 UTC, merged