feat(zimbra) : #MC-266 call eb when sync platform
OPEN-ENT-NG/calendar pull request #196
Opened 2023-01-03 14:12 UTC by alicedraillard

## Describe your changes
when sync is called, if the calendar is from a specific platform an eb is sent to the platform

## Checklist tests
sync calendar with platform

## Issue ticket number and link
[MC-266](https://jira.support-ent.fr/browse/MC-266)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-03 14:12 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/core/enums/ExternalICalEventBusActions.java
> -    CHECK_PLATFORM("check-platform");
unused variable

2023-01-03 14:12 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +            JsonObject requestInfo = new JsonObject().put(Field.DOMAIN, host).put(Field.ACCEPTLANGUAGE, i18nLang);
indentation start

2023-01-03 14:13 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +            });
indentation end

2023-01-03 14:25 UTC, sjollois approved these changes

2023-01-03 14:56 UTC, JinDouang requested changes

2023-01-03 14:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +
Possibilité de découper la méthode ? 

ton if, else if et else est plutôt volumineux, 3 méthodes promises pourraient potentiellement être crée ?

2023-01-03 15:24 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                    promise.fail(errMessage);
Si tu fail ta promise il faut pas que tu continue l'exécution de ton code. Actuelement tu va quand meme faire eb.request
qui risque de fail vu que ebAddress = "", et donc tu va re fail ta promise ligne 195.

promise.fail(errMessage)
return promise;

2023-01-03 16:51 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
> +                    promise.fail(message);
correct error from commit #194

2023-01-03 17:21 UTC, JinDouang approved these changes

2023-01-03 17:26 UTC, JinDouang requested changes

2023-01-03 17:26 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                promise.fail(errMessage);
A revoir, mettre simplement une clé erreur ou un message simple

2023-01-04 10:01 UTC, JinDouang requested changes

2023-01-04 10:01 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                promise.fail(errMessage);
Pour le promise.fail, utilise l'objet `event`

2023-01-04 10:01 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +    private void getICalFromExternalPlatform(UserInfos user, Promise<Void> promise, String platform) {
ne pas passer la promise en référence

2023-01-04 10:01 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +            promise.fail(errMessage);
log erreur manquant

ton promise.fail doit retourner une erreur fonctionnel

2023-01-04 10:01 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +    private void callLinkImportEventBus(UserInfos user, JsonObject calendar, String host, String i18nLang, String action, Promise<Void> promise) {
ne pas passer la promise en référence

2023-01-04 10:01 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
> +                    promise.fail(message);
A rectifier le log erreur et promise.fail

2023-01-04 10:12 UTC, JinDouang requested changes

2023-01-04 10:12 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                promise.fail("calendar.error.missing.data");
Ton erreur fonctionnel n'a pas de sens par rapport à ta méthode et ton log

2023-01-04 14:17 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/core/enums/ExternalPlatformEnum.java
> +    public String method() {
public String getEventBusAddress() {

2023-01-04 14:27 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/core/enums/ExternalPlatformEnum.java
> +    private final String externalPlatform;
eventBusAddress

2023-01-04 14:27 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                            "ics retrieval : object is missing data", this.getClass().getSimpleName());
Vu avec @alicedraillard, pas besoin de object is missing data

2023-01-04 14:27 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
>                  String errMessage = String.format("[Calendar@%s::getAndSaveExternalCalendarEvents]:  " +
[Calendar@%s::callLinkImportEventBus]

2023-01-04 14:27 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
> +            promise.fail(message);
Vu avec @alicedraillard "calendar.error.missing.data" ?

2023-01-04 15:10 UTC, BastienBenard approved these changes

2023-01-04 15:29 UTC, JinDouang requested changes

2023-01-04 15:29 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                    promise.fail(err);
```suggestion
                    promise.fail(err.getMessage());
```

2023-01-04 15:29 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                promise.fail(event.cause());
```suggestion
                promise.fail(event.cause().getMessage());
```

2023-01-04 15:29 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
> +                promise.fail("calendar.error.missing.data");
Pourquoi ne pas utiliser event.cause().getMessage() ?

2023-01-04 15:50 UTC, JinDouang approved these changes

2023-01-04 16:03 UTC, merged