fix(calendarEvent): #MC-297 disable save button when too old start date and too far end date
OPEN-ENT-NG/calendar pull request #219
Opened 2023-10-11 08:09 UTC by Gregprod33

## Describe your changes
To prevent user from saving too long events and slow down the application, we now display a message and disable save button if the start date of event is too old (before january 1, 2000) or end date is more than in 80 years.
## Checklist tests
Create a new event and choose a date before 01 01 2000 or a end date after 2103
## Issue ticket number and link
[MC-297](https://jira.support-ent.fr/browse/MC-297)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-10-12 13:52 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +            $scope.minDate = moment('2000-01-01');
Mets '2000-01-01' et 80 dans le fichier de const TIME.ts

2023-10-12 13:53 UTC, alicedraillard requested changes

2023-10-12 13:53 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/controller.ts
> +                    && $scope.isTimeValid() && $scope.isDateValid() &&  $scope.areRecurrenceAndEventLengthsCompatible() && !$scope.isStartDateToOld() && !$scope.isEndDateToFar());
il se passe quoi si on fait une requete postman avec un évent trop long ? --> vérif back en + peut-être ?

2023-10-12 14:11 UTC, qperie commented on src/main/resources/public/ts/controllers/controller.ts
> +            $scope.isStartDateToOld = (): boolean => ($scope.calendarEvent.startMoment < $scope.minDate);
Juste une histoire d'anglais mais c'est "isStartDateTooOld" avec 2 "oo" (3 avec celui de "Old")

2023-10-12 14:11 UTC, qperie commented on src/main/resources/public/ts/controllers/controller.ts
> +            $scope.isEndDateToFar = (): boolean => ($scope.calendarEvent.endMoment > $scope.maxDate);
Même remarque qu'au-dessus

2023-10-12 14:11 UTC, qperie commented on src/main/resources/public/ts/controllers/controller.ts
> +                    && $scope.isTimeValid() && $scope.isDateValid() &&  $scope.areRecurrenceAndEventLengthsCompatible() && !$scope.isStartDateToOld() && !$scope.isEndDateToFar());
Très bonne remarque

2023-10-16 09:02 UTC, qperie approved these changes

2023-10-16 15:14 UTC, FlorentMr commented on src/main/resources/public/ts/controllers/controller.ts
> +                if (end_type === 'on' && end_on) {
Vérification utile? (pas sûr de comprendre de pourquoi recurrence peut changer de type, j'ai pas le contexte)

2023-10-17 07:45 UTC, merged