fix(delete): #MC-123 display booking deletion checkbox
OPEN-ENT-NG/calendar pull request #84
Opened 2022-06-09 13:50 UTC by alicedraillard

## Describe your changes
fix #83 :
- check booking deletion rights
- changes in popup appearance

## Checklist tests
for many cases (author, shared with RBS manage right, shared with no RBS right ...):
calendar view : click on created event with booking and delete it, the message with choice appears in the confirmation popup
list view:

try to delete one event without booking : behaviour is same as before
try to delete one event with booking : behaviour is same as calendar view + the event edition window opens
try to delete many events including one with booking: message states that the deletion will not impact [[event with booking's name]]'s booking.

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)
#MC-123 https://entsupport.gdapublic.fr/browse/MC-123

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-09 13:51 UTC, alicedraillard commented on build.sh
> -  BRANCH_NAME=`echo $GIT_BRANCH | sed -e "s|origin/||g"`
commits will be squashed before merging

2022-06-09 13:57 UTC, BastienBenard commented on src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.ts
> +    canDeleteBooking = () => {
typage

2022-06-09 13:59 UTC, BastienBenard commented on src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
> +            rbsSnipletVm.bookings.all.find(b => b.resource && (b.resource.owner == model.me.userId));
typage de b

2022-06-09 14:00 UTC, BastienBenard commented on src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
> +            rbsSnipletVm.bookings.all.forEach(b => {
typage de b

2022-06-09 14:16 UTC, JinDouang requested changes

2022-06-09 14:16 UTC, JinDouang commented on src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.ts
> +    canDeleteBooking = ():boolean => {
indentation

2022-06-10 15:04 UTC, JinDouang requested changes

2022-06-10 15:04 UTC, JinDouang commented on src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
> +            let resourceTypeStructures: Array<String> = [];
String => string

2022-06-13 12:45 UTC, merged