feat(rbs): #MC-147 secure deletion back-end
OPEN-ENT-NG/calendar pull request #85
Opened 2022-06-16 10:07 UTC by alicedraillard

## Describe your changes
- delete bookings from event
- check rbs deletion rights before deleting the booking

## Checklist tests
try to delete bookings in the following cases:
- is booking creator
- is resource owner
- is ADML for the resource type's structure
- resource type was shared with validate or manag

## Issue ticket number and link
#MC-147 https://entsupport.gdapublic.fr/browse/MC-147

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-16 10:07 UTC, alicedraillard commented on build.sh
> -  echo "[buildNode] Get branch name from jenkins env..."
will be deleted before merge

2022-06-16 13:26 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +        QueryBuilder query = QueryBuilder.start(Field._ID).is(attachmentId);
refacto id field

2022-06-16 14:56 UTC, JinDouang requested changes

2022-06-16 14:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/core/constants/Field.java
> +    public static final String RBSADDRESS = "net.atos.entng.rbs";
c'est un donnée trop "importante" pour le catégoriser dans un "field" à mon sens...

2022-06-16 14:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/security/DeletedBookingRightsConf.java
> +    public void authorize(HttpServerRequest request, UserInfos user, EventServiceMongo eventServiceMongo, EventBus eb, Handler<Boolean> handler) {
Comme ca sera jamais utilisé dans la sécurité ResourceFilter, il pourrait retourner une Future de boolean non ?

2022-06-16 14:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/core/constants/Field.java
> +    public static final String DELETE_BOOKINGS = "delete-bookings";
Ils sont spécifiques non ?

2022-06-16 14:56 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/security/DeletedBookingRightsConf.java
> +            eventServiceMongo.retrieve(calendarId, eventId, user, event -> {
Tu mélanges ton business logic j'ai l'impression : 

Tu récupères un evenement pour avoir les infos sur les ressources
mais est-ce qu'il faudrait le faire ici ? pas sur un service p-e ?

2022-06-16 15:06 UTC, flmartineau commented on src/main/java/net/atos/entng/calendar/security/ShareBookingConf.java
> +            QueryBuilder query = QueryBuilder.start("_id").is(id).or(
Field._ID

2022-06-16 15:22 UTC, BastienBenard commented on src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
> +import static org.entcore.common.http.response.DefaultResponseHandler.notEmptyResponseHandler;
Il est utilisé cette import ?

2022-06-16 15:42 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/core/constants/Field.java
> +    public static final String DELETE_BOOKINGS = "delete-bookings";
ce sont des messages d'eb, tu aimerais que j'en fasse une classe à part ?

2022-06-17 14:05 UTC, alicedraillard commented on src/main/java/net/atos/entng/calendar/core/constants/Field.java
> +    public static final String DELETE_BOOKINGS = "delete-bookings";
messages d'event bus mis dans un enum

2022-06-20 09:48 UTC, JinDouang requested changes

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +//                new DeletedBookingRightsConf().authorize(request, user, eventServiceMongo, eb)
commentaire ?

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +    private final EventServiceMongo eventServiceMongo;
utilité ?

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +        eventServiceMongo = new EventServiceMongoImpl(collection, eb, serviceFactory);
utilité ?

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/core/enums/RbsEventBusActions.java
> +    private final String eventBusAction;
Tu peux ajouter l'adresse en dur ici aussi!

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
> +                    } else if (event.isLeft()) {
pourquoi else if ?

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
> +        eb.request(RBSADDRESS, action, messageBooleanHandler(handlerBoolean(promise)));
Pas nécessaire

2022-06-20 09:48 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/helpers/FutureHelper.java
> +    public static Handler<AsyncResult<Message<JsonObject>>> messageBooleanHandler(Handler<Either<String, Boolean>> handler) {
pas nécessaire

2022-06-20 12:41 UTC, JinDouang requested changes

2022-06-20 12:41 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +        UserUtils.getUserInfos(eb, request, user -> {
tu le refais dans l'autre méthode delete

2022-06-20 12:41 UTC, JinDouang commented on src/main/java/net/atos/entng/calendar/controllers/EventController.java
> +import java.util.regex.Pattern;
?

2022-06-21 08:42 UTC, merged